### ISSUE TITLE
Custom puppeteer requests

### ISSUE THREAD

**Issue by kuwaitman** [ispras/scrapy-puppeteer#25]
Hi, is there a way i can custom the puppeteer request, for example to add puppeteer extra functionality?

thank you.

**Comment by mxsnq** [comment]
Hi!

Some functionalities of Puppeteer that are not covered by our existing actions can be leveraged through CustomJsAction. This action allows you to execute custom JavaScript functions with access to [Puppeteer's Page object](https://pptr.dev/api/puppeteer.page). An example of such function can be found [here](https://github.com/ispras/scrapy-puppeteer-service?tab=readme-ov-file#action).

Other scenarious require patching [the service](https://github.com/ispras/scrapy-puppeteer-service). In order to use puppeteer-extra plugins you'll have to enable them in the [app.js module](https://github.com/ispras/scrapy-puppeteer-service/blob/master/app.js). Currently there are only puppeteer-extra-plugin-stealth and puppeteer-extra-plugin-recaptcha. Once enabled, you can access this functionality through CustomJsActions or by defining your own actions. For the latter, you'll need to define new PuppeteerServiceAction subclass on the client side and to add a corresponding action route in the service.
